name: GenerateReportPDF

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  GenerateReportPDF:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    container:
      image: pandoc/latex:3.8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Execute pandoc
        run: |
          pandoc report.md -o 2025_itubdsa_group_7_report.pdf

      - name: Upload result to Artifact storage
        uses: actions/upload-artifact@v6
        with:
          name: Report.zip
          path: "docs/2025_itubdsa_group_7_report.pdf"

      - name: Commit generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "2025_itubdsa_group_7_report.pdf"
          git commit -m "Generated report PDF."
          git push