name: GenerateReportPDF

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - '**'
  pull-request:
    paths:
      - 'docs/**'
    branches:
      - '**'
jobs:
  GenerateReportPDF:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/core:3.8
        with:
          args: docs/report.pdf -o docs/2025_itubdsa_group_7_report.pdf