name: GenerateReportPDF

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull-request:
    branches:
      - '**'
jobs:
  GenerateReportPDF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses:
          actions/checkout@v5
      - name: Change directory
        run:
          cd docs
      - name: Execute pandoc
        uses: docker://pandoc/core:3.8
        with:
          args: "report.md -o 2025_itubdsa_group_7_report.pdf"

      - name: Upload result to Artifact storage
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: docs/2025_itubdsa_group_7_report.pdf