name: GenerateReportPDF

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  GenerateReportPDF:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    container:
      image: pandoc/latex:3.8

    steps:
      - name: Checkout repository
        uses:
          actions/checkout@v5

      - name: Execute pandoc
        run: |
          pandoc report.md -o 2025_itubdsa_group_7_report.pdf

      - name: Upload result to Artifact storage
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: 2025_itubdsa_group_7_report.pdf