
name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: build
        run: dotnet build
        
      - name: download-playwright
        run: pwsh ./tests/PlaywrightTests/bin/Debug/net9.0/playwright.ps1 install
      - name: Test
        run: |
          export authenticationGitHubClientId="${{ secrets.GITHUBCLIENTID }}"
          export authenticationGitHubClientSecret="${{ secrets.GITHUBCLIENTSECRET }}"
          dotnet test -e ASPNETCORE_ENVIRONMENT=Development --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: publish
        run: |
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -r win-x64 -c Release -o Published/Windows --self-contained true -p:PublishSingleFile=true
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -r osx-x64 -c Release -o Published/MacOS --self-contained true -p:PublishSingleFile=true
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -r linux-x64 -c Release -o Published/Linux --self-contained true -p:PublishSingleFile=true
      - name: copyDatabace
        run: |
          cp src/Chirp.Infrastructure/data/Chirp.db Published/Windows/data/Chirp.db
          cp src/Chirp.Infrastructure/data/Chirp.db Published/MacOS/data/Chirp.db
          cp src/Chirp.Infrastructure/data/Chirp.db Published/Linux/data/Chirp.db
      - name: zipFiles
        run: |
          zip -r Chirp-Win.zip Published/Windows
          zip -r Chirp-MacOS.zip Published/MacOS
          zip -r Chirp-Linux.zip Published/Linux
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Chirp-Win.zip
            Chirp-MacOS.zip
            Chirp-Linux.zip